name: ~ Example Reusable Nested
on:
  workflow_call:
    inputs:
      workflow-context:
        type: string

jobs:
  build-with-reusable-workflow:
    uses: ./.github/workflows/example-reusable.yml
