name: ~Reusable Example
on:
  workflow_call:

permissions:
  contents: read
  actions: read
  deployments: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
